name: diurecycle
description: "DIU Recycle is a Flutter-based mobile application designed to facilitate buying and selling used products among students of Daffodil International University (DIU). The platform promotes sustainability and convenience by connecting buyers and sellers within the university community."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

homepage: https://github.com/syedsabbir-git/DIU-Recycle
repository: https://github.com/syedsabbir-git/DIU-Recycle
issue_tracker: https://github.com/syedsabbir-git/DIU-Recycle/issues

environment:
  sdk: ^3.6.0

# consider running `flutter pub upgrade --major-versions`.

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  firebase_storage: ^13.0.4
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  cloud_firestore: ^6.1.0
  http: ^1.3.0
  timeline_tile: ^2.0.0
  shimmer: ^3.0.0
  flutter_image_compress: ^2.4.0
  lottie: ^3.3.0
  connectivity_plus: ^7.0.0
  logger: ^2.5.0
  logging: ^1.3.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  url_launcher: ^6.3.1
  csv: ^6.0.0
  printing: ^5.13.4
  fl_chart: ^1.1.1
  dart_openai: ^5.0.0
  envied: ^1.1.1
  google_generative_ai: ^0.4.6
  cloudinary_public: ^0.23.1
  flutter_launcher_icons: ^0.14.3
  maps_launcher: ^3.0.0+1
  cupertino_icons: ^1.0.8
  rename: ^3.0.2
  firebase_messaging: ^16.0.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_database: ^12.0.4
  onesignal_flutter: ^5.3.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  # adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  envied_generator: ^1.1.0
  build_runner: ^2.4.0

flutter:
  assets:
    - lib/assets/logo.png
  uses-material-design: true
